/** Auto-generated Việt hóa mở rộng cho lunar-typescript — chạy: node scripts/gen-lunar-vi.mjs */
export const EXTRA_VI: Record<string, string> = {
  "参星造作旺人家，文星照耀大光华，只因造作田财旺，埋葬招疾哭黄沙，开门放水加官职，房房子孙见田加，婚姻许遁遭刑克，男女朝开幕落花。": "Tú Sâm: làm nhà và mở cửa tốt; chôn cất và cưới hỏi kém.",
  "井星造作旺蚕田，金榜题名第一光，埋葬须防惊卒死，狂颠风疾入黄泉，开门放水招财帛，牛马猪羊旺莫言，贵人田塘来入宅，儿孙兴旺有余钱。": "Tú Tỉnh: làm nhà, mở cửa tốt; kiêng chôn cất— đề phòng chết đột ngột.",
  "鬼星起造卒人亡，堂前不见主人郎，埋葬此日官禄至，儿孙代代近君王，开门放水须伤死，嫁娶夫妻不久长，修土筑墙伤产女，手扶双女泪汪汪。": "Tú Quỷ: kiêng khởi tạo, mở cửa, cưới hỏi; chôn cất thì quan lộ tốt.",
  "柳星造作主遭官，昼夜偷闭不暂安，埋葬瘟惶多疾病，田园退尽守冬寒，开门放水遭聋瞎，腰驼背曲似弓弯，更有棒刑宜谨慎，妇人随客走盘桓。": "Tú Liễu: dễ quan sự, bệnh tật; kiêng làm nhà, chôn cất, mở cửa.",
  "星宿日好造新房，进职加官近帝王，不可埋葬并放水，凶星临位女人亡，生离死别无心恋，要自归休别嫁郎，孔子九曲殊难度，放水开门天命伤。": "Tú Tinh: tốt dựng nhà mới; kiêng chôn cất và xả nước/mở cửa.",
  "张星日好造龙轩，年年并见进庄田，埋葬不久升官职，代代为官近帝前，开门放水招财帛，婚姻和合福绵绵，田蚕人满仓库满，百般顺意自安然。": "Tú Trương: tốt làm nhà, chôn cất, cưới hỏi, mở cửa.",
  "翼星不利架高堂，三年二载见瘟惶，埋葬若还逢此日，子孙必定走他乡，婚姻此日不宜利，归家定是不相当，开门放水家须破，少女恋花贪外郎。": "Tú Dực: bất lợi nhà cao; kiêng chôn cất, cưới hỏi, mở cửa.",
  "轸星临水造龙宫，代代为官受皇封，富贵荣华增寿禄，库满仓盈自昌隆，埋葬文昌来照助，宅舍安宁不见凶，更有为官沾帝宠，婚姻龙子入龙宫。": "Tú Chẩn: rất tốt— làm nhà, chôn cất, cưới hỏi đều hanh thông.",
  "角星造作主荣昌，外进田财及女郎，嫁娶婚姻出贵子，文人及第见君王，惟有埋葬不可用，三年之后主瘟疫，起工修筑坟基地，堂前立见主人凶。": "Tú Giác: làm nhà thịnh vượng, cưới hỏi sinh quý tử; kiêng chôn cất kẻo bệnh dịch, chủ nhà bất lợi.",
  "亢星造作长房当，十日之中主有殃，田地消磨官失职，接运定是虎狼伤，嫁娶婚姻用此日，儿孙新妇守空房，埋葬若还用此日，当时害祸主重伤。": "Tú Cang: bất lợi trưởng phòng; cưới hỏi và chôn cất dễ họa lớn.",
  "氐星造作主灾凶，费尽田园仓库空，埋葬不可用此日，悬绳吊颈祸重重，若是婚姻离别散，夜招浪子入房中，行船必定遭沉没，更生聋哑子孙穷。": "Tú Đê: hao tài; kiêng chôn cất và cưới hỏi— ly tán, nghèo khó.",
  "房星造作田园进，钱财牛马遍山岗，更招外处田庄宅，荣华富贵福禄康，埋葬若然用此日，高官进职拜君王，嫁娶嫦娥至月殿，三年抱子至朝堂。": "Tú Phòng: làm nhà, chôn cất, cưới hỏi đều tốt— tài lộc quan lộ hanh thông.",
  "心星造作大为凶，更遭刑讼狱囚中，忤逆官非宅产退，埋葬卒暴死相从，婚姻若是用此日，子死儿亡泪满胸，三年之内连遭祸，事事教君没始终。": "Tú Tâm: đại hung— kiêng làm nhà, chôn cất, cưới hỏi.",
  "尾星造作主天恩，富贵荣华福禄增，招财进宝兴家宅，和合婚姻贵子孙，埋葬若能依此日，男清女正子孙兴，开门放水招田宅，代代公侯远播名。": "Tú Vĩ: rất tốt cho làm nhà, cưới hỏi, chôn cất.",
  "箕星造作主高强，岁岁年年大吉昌，埋葬修坟大吉利，田蚕牛马遍山岗，开门放水招田宅，箧满金银谷满仓，福荫高官加禄位，六亲丰禄乐安康。": "Tú Cơ: đại cát— làm nhà, chôn cất, mở cửa đều tốt.",
  "斗星造作主招财，文武官员位鼎台，田宅家财千万进，坟堂修筑贵富来，开门放水招牛马，旺蚕男女主和谐，遇此吉宿来照护，时支福庆永无灾。": "Tú Đẩu: chiêu tài, quan lộ tốt, làm mộ và mở cửa tốt.",
  "牛星造作主灾危，九横三灾不可推，家宅不安人口退，田蚕不利主人衰，嫁娶婚姻皆自损，金银财谷渐无之，若是开门并放水，牛猪羊马亦伤悲。": "Tú Ngưu: hung— kiêng làm nhà, cưới hỏi, mở cửa.",
  "女星造作损婆娘，兄弟相嫌似虎狼，埋葬生灾逢鬼怪，颠邪疾病主瘟惶，为事遭官财失散，泻利留连不可当，开门放水用此日，全家财散主离乡。": "Tú Nữ: hại nữ giới; kiêng chôn cất và mở cửa.",
  "虚星造作主灾殃，男女孤眠不一双，内乱风声无礼节，儿孙媳妇伴人床，开门放水遭灾祸，虎咬蛇伤又卒亡，三三五五连年病，家破人亡不可当。": "Tú Hư: tai ương gia đạo; kiêng mở cửa/xả nước.",
  "危星不可造高楼，自遭刑吊见血光，三年孩子遭水厄，后生出外永不还，埋葬若还逢此日，周年百日取高堂，三年两载一悲伤，开门放水到官堂。": "Tú Nguy: kiêng xây cao, chôn cất, mở cửa.",
  "室星修造进田牛，儿孙代代近王侯，家贵荣华天上至，寿如彭祖八千秋，开门放水招财帛，和合婚姻生贵儿，埋葬若能依此日，门庭兴旺福无休。": "Tú Thất: tốt cho tu tạo, cưới hỏi, chôn cất.",
  "壁星造作主增财，丝蚕大熟福滔天，奴婢自来人口进，开门放水出英贤，埋葬招财官品进，家中诸事乐陶然，婚姻吉利主贵子，早播名誉著祖鞭。": "Tú Bích: tăng tài; cưới hỏi và chôn cất tốt.",
  "奎星造作得祯祥，家内荣和大吉昌，若是埋葬阴卒死，当年定主两三伤，看看军令刑伤到，重重官事主瘟惶，开门放水遭灾祸，三年两次损儿郎。": "Tú Khuê: làm nhà tạm được; kiêng chôn cất và mở cửa.",
  "娄星修造起门庭，财旺家和事事兴，外进钱财百日进，一家兄弟播高名，婚姻进益生贵子，玉帛金银箱满盈，放水开门皆吉利，男荣女贵寿康宁。": "Tú Lâu: tu tạo, cưới hỏi, mở cửa đều tốt.",
  "胃星造作事如何，家贵荣华喜气多，埋葬贵临官禄位，夫妇齐眉永保康，婚姻遇此家富贵，三灾九祸不逢他，从此门前多吉庆，儿孙代代拜金阶。": "Tú Vị: làm nhà, chôn cất, cưới hỏi đều tốt.",
  "昴星造作进田牛，埋葬官灾不得休，重丧二日三人死，尽卖田园不记增，开门放水招灾祸，三岁孩儿白了头，婚姻不可逢此日，死别生离是可愁。": "Tú Mão: làm nhà tạm được; kiêng chôn cất, cưới hỏi, mở cửa.",
  "毕星造作主光前，买得田园有余钱，埋葬此日添官职，田蚕大熟永丰年，开门放水多吉庆，合家人口得安然，婚姻若得逢此日，生得孩儿福寿全。": "Tú Tất: tốt cho làm nhà, chôn cất, cưới hỏi, mở cửa.",
  "觜星造作有徒刑，三年必定主伶丁，埋葬卒死多因此，取定寅年使杀人，三丧不止皆由此，一人药毒二人身，家门田地皆退败，仓库金银化作尘。": "Tú Tuy: hung— dễ hình sự, chết đột ngột; kiêng làm nhà và chôn cất.",
  "东北方度仙上圣天尊同梵炁始青天君下降": "Đông Bắc phươngĐộ Tiên Thượng Thánh Thiên tônđồng Phạm Khí Thủy Thanh Thiên Quân giáng thế",
  "东南方好生度命天尊同梵炁始丹天君下降": "Đông Nam phươngHảo Sinh Độ Mệnh Thiên tônđồng Phạm Khí Thủy Đan Thiên Quân giáng thế",
  "西南方太灵虚皇天尊同梵炁始素天君下降": "Tây Nam phươngThái Linh Hư Hoàng Thiên tônđồng Phạm Khí Thủy Tố Thiên Quân giáng thế",
  "西北方无量太华天尊同梵炁始玄天君下降": "Tây Bắc phươngVô Lượng Thái Hoa Thiên tônđồng Phạm Khí Thủy Huyền Thiên Quân giáng thế",
  "虚靖天师(即三十代天师弘悟张真人)诞": "Hư Tĩnh Thiên sư(tức Tam Thập Đại Thiên sưHoằng Ngộ Trương Chân nhân) đản",
  "东方玉宝星上天尊同青帝九炁天君下降": "Đông phươngNgọc Bảo Tinh Thượng Thiên tônđồng Thanh Đế Cửu Khí Thiên Quân giáng thế",
  "南方玄真万福天尊同赤帝三炁天君下降": "Nam phươngHuyền Chân Vạn Phúc Thiên tônđồng Xích Đế Tam Khí Thiên Quân giáng thế",
  "西方太妙至极天尊同白帝七炁天君下降": "Tây phươngThái Diệu Chí Cực Thiên tônđồng Bạch Đế Thất Khí Thiên Quân giáng thế",
  "北方玄上玉宸天尊同黑帝五炁天君下降": "Bắc phươngHuyền Thượng Ngọc Thần Thiên tônđồng Hắc Đế Ngũ Khí Thiên Quân giáng thế",
  "财帛星君文财神增福相公李诡祖圣诞": "Tài Bạch Tinh quânVăn Thần TàiTăng Phúc Tướng Công Lý Quỷ Tổ đản sinh",
  "太清道德天尊(太上老君)圣诞": "Thái ThanhĐạo Đức Thiên Tôn(Thái Thượng Lão Quân) đản sinh",
  "谭祖(谭处端)长真真人圣诞": "Đàm Tổ (Đàm Xử Đoan)Trường Chân Chân nhân đản sinh",
  "王祖(王处一)玉阳真人圣诞": "Vương Tổ (Vương Xử Nhất)Ngọc Dương Chân nhân đản sinh",
  "刘祖(刘处玄)长生真人圣诞": "Lưu Tổ (Lưu Xử Huyền)Trường Sinh Chân nhân đản sinh",
  "清静孙真君(孙不二)成道": "Thanh Tĩnh Tôn Chân quân(Tôn Bất Nhị) thành đạo",
  "长春邱真人(邱处机)圣诞": "Trường Xuân Khâu Chân nhân(Khâu Xử Cơ) đản sinh",
  "长春刘真人(刘渊然)圣诞": "Trường Xuân Lưu Chân nhân(Lưu Uyên Nhiên) đản sinh",
  "全国中小学生安全教育日": "Ngày giáo dục an toàn học sinh (TQ)",
  "许真君(许逊天师)圣诞": "Hứa Chân quân(Hứa Tốn Thiên sư) đản sinh",
  "sn.sanSang": "Tam Tang",
  "天曹诸司五岳五帝圣诞": "Thiên Tào Chư Tư Ngũ Nhạc Ngũ Đế đản sinh",
  "南极大帝中方雷祖圣诞": "Nam Cực Đại đếTrung phươngLôi Tổ đản sinh",
  "度人无量葛真君圣诞": "Độ Nhân Vô Lượng Cát Chân quân đản sinh",
  "长生谭真君成道之辰": "Trường Sinh Đàm Chân quân thành đạo",
  "泰山圣母碧霞元君诞": "Thái Sơn Thánh Mẫu Bích Hà Nguyên quân đản",
  "慈航(观音)成道日": "Từ Hàng(Quán Âm) ngày thành đạo",
  "五显灵官马元帅圣诞": "Ngũ Hiển Linh Quan Mã Nguyên soái đản sinh",
  "天气上升地气下降": "Khí trời lên, khí đất xuống",
  "甲不开仓财物耗散": "Giáp— không mở kho, của cải tiêu tán",
  "乙不栽植千株不长": "Ất— không trồng cây, nghìn gốc khó lớn",
  "丙不修灶必见灾殃": "Bính— không sửa bếp, ắt gặp tai ương",
  "丁不剃头头必生疮": "Đinh— không cạo đầu, đầu ắt sinh ghẻ",
  "戊不受田田主不祥": "Mậu— không nhận ruộng, chủ ruộng chẳng lành",
  "己不破券二比并亡": "Kỷ— không phá khế, hai bên cùng hại",
  "庚不经络织机虚张": "Canh— không kinh lạc, khung cửi hư không",
  "辛不合酱主人不尝": "Tân— không làm tương, chủ không nếm",
  "壬不泱水更难提防": "Nhâm— không khơi nước, càng khó đề phòng",
  "癸不词讼理弱敌强": "Quý— không kiện tụng, lý yếu địch mạnh",
  "子不问卜自惹祸殃": "Tý— không hỏi quẻ, tự chuốc họa",
  "丑不冠带主不还乡": "Sửu— không đội mũ đeo đai, khó về quê",
  "寅不祭祀神鬼不尝": "Dần— không tế tự, thần quỷ chẳng hưởng",
  "寅不祭祀神鬼怒伤": "Dần— không tế tự, thần quỷ giận hại",
  "卯不穿井水泉不香": "Mão— không đào giếng, nước suối chẳng trong",
  "辰不哭泣必主重丧": "Thìn— không khóc lóc, ắt gặp đại tang",
  "巳不远行财物伏藏": "Tỵ— không đi xa, của cải ẩn giấu",
  "午不苫盖屋主更张": "Ngọ— không lợp nhà, chủ nhà xáo động",
  "未不服药毒气入肠": "Mùi— không uống thuốc, độc khí vào ruột",
  "申不安床鬼祟入房": "Thân— không an giường, quỷ vào phòng",
  "酉不会客醉坐颠狂": "Dậu— không hội khách, say sưa loạn cuồng",
  "酉不宴客醉坐颠狂": "Dậu— không đãi khách, say sưa loạn cuồng",
  "戌不吃犬作怪上床": "Tuất— không ăn thịt chó, quái lên giường",
  "亥不嫁娶不利新郎": "Hợi— không cưới hỏi, bất lợi chú rể",
  "sn.guiKu": "Quỷ Khốc",
  "勾陈天皇大帝圣诞": "Câu Trần Thiên Hoàng Đại đế đản sinh",
  "文昌梓潼帝君圣诞": "Văn Xương Tử Đồng Đế Quân đản sinh",
  "天师张大真人圣诞": "Thiên sưTrương Đại Chân nhân đản sinh",
  "财神赵公元帅圣诞": "Thần TàiTriệu Công Nguyên soái đản sinh",
  "三茅真君得道之辰": "Tam Mao Chân quân đắc đạo",
  "吕祖纯阳祖师圣诞": "Lã TổThuần Dương Tổ sư đản sinh",
  "北极紫微大帝圣诞": "Bắc Cực Tử Vi Đại đế đản sinh",
  "南极长生大帝圣诞": "Nam Cực Trường Sinh Đại đế đản sinh",
  "马祖丹阳真人圣诞": "Mã Tổ Đan Dương Chân nhân đản sinh",
  "中元地官大帝圣诞": "Trung NguyênĐịa Quan Đại đế đản sinh",
  "北斗九皇降世之辰": "Bắc Đẩu Cửu Hoàng Giáng Thế",
  "三茅应化真君圣诞": "Tam Mao Ứng Hóa Chân quân đản sinh",
  "下元水官大帝圣诞": "Hạ NguyênThủy Quan Đại đế đản sinh",
  "太乙救苦天尊圣诞": "Thái Ất Cứu Khổ Thiên tôn đản sinh",
  "全民国防教育日": "Ngày giáo dục quốc phòng (TQ)",
  "孙祖清静元君诞": "Tôn Tổ Thanh Tĩnh Nguyên quân đản",
  "华佗神医先师诞": "Hoa Đà Thần Y Tiên sư đản",
  "眼光圣母娘娘诞": "Nhãn Quang Thánh Mẫu Nương nương đản",
  "地祗温元帅圣诞": "Địa Chi Ôn Nguyên soái đản sinh",
  "雷霆邓天君圣诞": "Lôi Đình Đặng Thiên Quân đản sinh",
  "紫青白祖师圣诞": "Tử Thanh Bạch Tổ sư đản sinh",
  "刘海蟾祖师圣诞": "Lưu Hải Thiềm Tổ sư đản sinh",
  "灵官王天君圣诞": "Linh Quan Vương Thiên Quân đản sinh",
  "九天司命灶君诞": "Cửu Thiên Tư Mệnh Táo quân đản",
  "长春邱真君飞升": "Trường Xuân Khâu Chân quân phi thăng",
  "张三丰祖师圣诞": "Trương Tam Phong Tổ sư đản sinh",
  "雀入大水为蛤": "Chim sẻ vào nước lớn hóa nghêu",
  "雉入大水为蜃": "Trĩ vào nước lớn hóa sò",
  "消费者权益日": "Ngày quyền lợi người tiêu dùng",
  "北方五道圣诞": "Bắc phươngNgũ Đạo đản sinh",
  "南岳大帝圣诞": "Nam Nhạc Đại đế đản sinh",
  "重阳祖师圣诞": "Trùng Dương Tổ sư đản sinh",
  "玉皇上帝圣诞": "Ngọc Hoàng Thượng đế đản sinh",
  "关圣帝君飞升": "Quan Thánh Đế quân phi thăng",
  "上元天官圣诞": "Thượng NguyênThiên Quan đản sinh",
  "老祖天师圣诞": "Lão Tổ Thiên sư đản sinh",
  "东华帝君圣诞": "Đông Hoa Đế Quân đản sinh",
  "慈航真人圣诞": "Từ Hàng Chân nhân đản sinh",
  "玄天上帝圣诞": "Huyền Thiên Thượng Đế đản sinh",
  "眼光娘娘圣诞": "Nhãn Quang Nương nương đản sinh",
  "中岳大帝圣诞": "Trung Nhạc Đại đế đản sinh",
  "后土娘娘圣诞": "Hậu Thổ Nương nương đản sinh",
  "太阳星君圣诞": "Thái Dương Tinh quân đản sinh",
  "子孙娘娘圣诞": "Tử Tôn Nương nương đản sinh",
  "天后妈祖圣诞": "Thiên HậuMa Tổ đản sinh",
  "东岳大帝圣诞": "Đông Nhạc Đại đế đản sinh",
  "钟离祖师圣诞": "Chung Ly Tổ sư đản sinh",
  "南方雷祖圣诞": "Nam phươngLôi Tổ đản sinh",
  "关圣帝君降神": "Quan Thánh Đế quân giáng thần",
  "关平太子圣诞": "Quan Bình Thái Tử đản sinh",
  "灵宝天尊圣诞": "Linh Bảo Thiên tôn đản sinh",
  "南斗星君下降": "Nam Đẩu Tinh quân giáng thế",
  "西方雷祖圣诞": "Tây phươngLôi Tổ đản sinh",
  "王母娘娘圣诞": "Vương Mẫu Nương nương đản sinh",
  "许真君飞升日": "Hứa Chân quân phi thăngNhật",
  "北方雷祖圣诞": "Bắc phươngLôi Tổ đản sinh",
  "北岳大帝诞辰": "Bắc Nhạc Đại đế đản thần",
  "斗姥元君圣诞": "Đẩu Mẫu Nguyên quân đản sinh",
  "重阳帝君圣诞": "Trùng DươngĐế Quân đản sinh",
  "玄天上帝飞升": "Huyền Thiên Thượng Đế phi thăng",
  "酆都大帝圣诞": "Phong Đô Đại đế đản sinh",
  "萨翁真君圣诞": "Tát Ông Chân quân đản sinh",
  "东皇大帝圣诞": "Đông Hoàng Đại đế đản sinh",
  "地母娘娘圣诞": "Địa Mẫu Nương nương đản sinh",
  "西岳大帝圣诞": "Tây Nhạc Đại đế đản sinh",
  "湘子韩祖圣诞": "Tương Tử Hàn Tổ đản sinh",
  "元始天尊圣诞": "Nguyên Thủy Thiên tôn đản sinh",
  "鲁班先师圣诞": "Lỗ Ban Tiên sư đản sinh",
  "天猷上帝圣诞": "Thiên Du Thượng đế đản sinh",
  "关圣帝君圣诞": "Quan Thánh Đế quân đản sinh",
  "二郎真君圣诞": "Nhị Lang Chân quân đản sinh",
  "田鼠化为鴽": "Chuột đồng hóa thành chim",
  "鸣鸠拂其羽": "Cưu vỗ cánh",
  "戴胜降于桑": "Chim đội thắng đậu trên dâu",
  "闭塞而成冬": "Bế tắc thành đông",
  "全国助残日": "Ngày hỗ trợ người khuyết tật (TQ)",
  "世界住房日": "Ngày Nhà ở Thế giới",
  "王侯腊之辰": "Vương Hầu Lạp",
  "福德正神诞": "Phúc Đức Chính Thần đản",
  "郝真人圣诞": "Hách Chân nhân đản sinh",
  "孙真人圣诞": "Tôn Chân nhân đản sinh",
  "土地正神诞": "Thổ địaChính Thần đản",
  "姜太公圣诞": "Khương Thái Công đản sinh",
  "鬼谷先师诞": "Quỷ Cốc Tiên sư đản",
  "何仙姑圣诞": "Hà Tiên Cô đản sinh",
  "神农先帝诞": "Thần Nông Tiên Đế đản",
  "城隍爷圣诞": "Thành HoàngGia đản sinh",
  "张天师圣诞": "Trương Thiên sư đản sinh",
  "道德腊之辰": "Đạo Đức Lạp",
  "太阴星君诞": "Thái Âm Tinh quân đản",
  "增福财神诞": "Tăng Phúc Thần Tài đản",
  "民岁腊之辰": "Dân Tuế Lạp",
  "东风解冻": "Đông phong giải đông",
  "蛰虫始振": "Trùng ngủ đông bắt đầu dậy",
  "鱼陟负冰": "Cá nổi mang băng",
  "草木萌动": "Cây cỏ nảy mầm",
  "鹰化为鸠": "Ưng hóa thành cưu",
  "雷乃发声": "Sấm bắt đầu vang",
  "反舌无声": "Chim phản thiệt im tiếng",
  "蟋蟀居壁": "Dế trú tường",
  "腐草为萤": "Cỏ mục hóa đom đóm",
  "土润溽暑": "Đất ẩm nắng oi",
  "大雨行时": "Mưa lớn đúng mùa",
  "鹰乃祭鸟": "Ưng tế chim",
  "天地始肃": "Trời đất bắt đầu nghiêm",
  "群鸟养羞": "Chim chứa thức ăn",
  "雷始收声": "Sấm bắt đầu tắt",
  "蛰虫坯户": "Trùng đắp hang",
  "鸿雁来宾": "Hồng nhạn đến làm khách",
  "菊有黄花": "Cúc nở vàng",
  "豺乃祭兽": "Sói tế thú",
  "草木黄落": "Cây cỏ vàng rụng",
  "蛰虫咸俯": "Trùng đều ẩn",
  "虹藏不见": "Cầu vồng ẩn mất",
  "鹖鴠不鸣": "Hạt đán không kêu",
  "征鸟厉疾": "Chim chinh lanh lợi",
  "水泽腹坚": "Đầm nước đóng cứng",
  "阳破阴冲": "Dương phá âm xung",
  "五谷母节": "Tiết Ngũ Cốc Mẫu",
  "玉帝巡天": "Ngọc Đế tuần thiên",
  "天神下降": "Thiên thần giáng thế",
  "天腊之辰": "Thiên Lạp",
  "举迁赏会": "Cử thiên thưởng hội",
  "地腊之辰": "Địa Lạp",
  "火神圣诞": "Hỏa Thần đản sinh",
  "庆生中会": "Khánh sinh trung hội",
  "建生大会": "Kiến sinh đại hội",
  "獭祭鱼": "Rái cá tế cá",
  "候雁北": "Nhạn chờ bay về Bắc",
  "桃始华": "Đào bắt đầu nở",
  "仓庚鸣": "Hoàng oanh hót",
  "玄鸟至": "Huyền điểu đến",
  "桐始华": "Ngô đồng bắt đầu nở",
  "虹始见": "Cầu vồng bắt đầu hiện",
  "萍始生": "Bèo bắt đầu sinh",
  "蝼蝈鸣": "Dế kêu",
  "蚯蚓出": "Giun đất ra",
  "王瓜生": "Dưa vàng sinh",
  "苦菜秀": "Rau đắng tốt",
  "靡草死": "Cỏ mềm chết",
  "麦秋至": "Lúa mạch vào mùa",
  "螳螂生": "Bọ ngựa sinh",
  "鵙始鸣": "Bách thanh bắt đầu hót",
  "鹿角解": "Gạc hươu rụng",
  "蜩始鸣": "Ve bắt đầu kêu",
  "半夏生": "Bán hạ sinh",
  "温风至": "Gió ấm đến",
  "鹰始挚": "Ưng bắt đầu săn",
  "凉风至": "Gió mát đến",
  "白露降": "Bạch lộ giáng",
  "寒蝉鸣": "Ve lạnh kêu",
  "禾乃登": "Lúa chín",
  "鸿雁来": "Hồng nhạn đến",
  "玄鸟归": "Huyền điểu về",
  "水始涸": "Nước bắt đầu cạn",
  "水始冰": "Nước bắt đầu đóng băng",
  "地始冻": "Đất bắt đầu đóng băng",
  "虎始交": "Hổ bắt đầu giao",
  "荔挺出": "Lai đĩnh nhú",
  "蚯蚓结": "Giun đất kết",
  "麋角解": "Gạc nai rụng",
  "水泉动": "Suối nước động",
  "雁北乡": "Nhạn hướng Bắc",
  "鹊始巢": "Quạ bắt đầu làm tổ",
  "雉始雊": "Trĩ bắt đầu gáy",
  "鸡始乳": "Gà bắt đầu ấp",
  "蛾眉新": "Nga mi mới",
  "蛾眉残": "Nga mi tàn",
  "渐盈凸": "Tiệm doanh đột",
  "渐亏凸": "Tiệm khuy đột",
  "仓库厕": "Kho/ nhà vệ sinh",
  "仓库床": "Kho/ giường",
  "仓库栖": "Kho/ chuồng",
  "仓库炉": "Kho/ lò",
  "仓库碓": "Kho/ cối",
  "仓库门": "Kho/ cửa",
  "厨灶厕": "Bếp/ nhà vệ sinh",
  "厨灶床": "Bếp/ giường",
  "厨灶栖": "Bếp/ chuồng",
  "厨灶炉": "Bếp/ lò",
  "厨灶碓": "Bếp/ cối",
  "厨灶门": "Bếp/ cửa",
  "房床厕": "Phòng giường/ nhà vệ sinh",
  "房床栖": "Phòng giường/ chuồng",
  "房床炉": "Phòng giường/ lò",
  "房床碓": "Phòng giường/ cối",
  "房床门": "Phòng giường/ cửa",
  "碓磨厕": "Cối xay/ nhà vệ sinh",
  "碓磨床": "Cối xay/ giường",
  "碓磨栖": "Cối xay/ chuồng",
  "碓磨炉": "Cối xay/ lò",
  "碓磨门": "Cối xay/ cửa",
  "占厕户": "Chiếm cửa nhà vệ sinh",
  "占厨灶": "Chiếm bếp",
  "占大门": "Chiếm cổng lớn",
  "占床仓": "Chiếm giường/ kho",
  "占户窗": "Chiếm cửa sổ",
  "占房床": "Chiếm phòng giường",
  "占灶炉": "Chiếm lò bếp",
  "占碓磨": "Chiếm cối xay",
  "占门厕": "Chiếm cửa nhà vệ sinh",
  "占门堂": "Chiếm cửa nhà",
  "占门床": "Chiếm cửa giường",
  "占门房": "Chiếm cửa phòng",
  "占门栖": "Chiếm cửa chuồng",
  "占门炉": "Chiếm cửa lò",
  "占门碓": "Chiếm cửa cối",
  "房内东": "trong phòng phía Đông",
  "房内南": "trong phòng phía Nam",
  "房内西": "trong phòng phía Tây",
  "房内北": "trong phòng phía Bắc",
  "房内中": "trong phòng giữa",
  "外正东": "ngoài chính Đông",
  "外正南": "ngoài chính Nam",
  "外正西": "ngoài chính Tây",
  "外正北": "ngoài chính Bắc",
  "外东南": "ngoài Đông Nam",
  "外东北": "ngoài Đông Bắc",
  "外西南": "ngoài Tây Nam",
  "外西北": "ngoài Tây Bắc",
  "一白水": "Nhất Bạch Thủy",
  "二黑土": "Nhị Hắc Thổ",
  "三碧木": "Tam Bích Mộc",
  "四绿木": "Tứ Lục Mộc",
  "五黄土": "Ngũ Hoàng Thổ",
  "六白金": "Lục Bạch Kim",
  "七赤金": "Thất Xích Kim",
  "八白土": "Bát Bạch Thổ",
  "九紫火": "Cửu Tử Hỏa",
  "元宵节": "Tết Nguyên tiêu",
  "龙头节": "Tết đầu rồng",
  "上巳节": "Thượng Tỵ",
  "寒食节": "Hàn thực",
  "清明节": "Tiết Thanh Minh",
  "端午节": "Tết Đoan Ngọ",
  "七夕节": "Thất tịch",
  "中元节": "Tết Trung Nguyên",
  "中秋节": "Tết Trung Thu",
  "重阳节": "Tết Trùng Dương",
  "下元节": "Tết Hạ Nguyên",
  "腊八节": "Tết Lạp Bát",
  "祭灶日": "Ngày cúng Táo",
  "中和节": "Tiết Trung Hòa",
  "社日节": "Tiết Xã nhật",
  "填仓节": "Tiết Điền Thương",
  "天穿节": "Tiết Thiên Xuyên",
  "天贶节": "Tiết Thiên Kuống",
  "分龙节": "Tiết Phân Long",
  "观莲节": "Tiết Ngắm sen",
  "地藏节": "Tiết Địa Tạng",
  "寒衣节": "Tiết Hàn Y",
  "天灸日": "Ngày Thiên Cứu",
  "接神日": "Ngày đón thần",
  "顺星节": "Tiết Thuận Tinh",
  "驱傩日": "Ngày Khu Na",
  "隔开日": "Ngày Cách Khai",
  "正月晦": "Hối tháng Giêng",
  "财神节": "Tiết Thần Tài",
  "十成节": "Tiết Thập Thành",
  "会龙节": "Tiết Hội Long",
  "元旦节": "Tết Dương lịch",
  "情人节": "Ngày Valentine",
  "妇女节": "Ngày Quốc tế Phụ nữ",
  "植树节": "Ngày trồng cây",
  "愚人节": "Ngày Cá tháng Tư",
  "劳动节": "Ngày Lao động",
  "青年节": "Ngày Thanh niên",
  "母亲节": "Ngày của Mẹ",
  "儿童节": "Ngày Thiếu nhi",
  "父亲节": "Ngày của Cha",
  "建党节": "Ngày thành lập Đảng (TQ)",
  "建军节": "Ngày thành lập quân đội (TQ)",
  "教师节": "Ngày Nhà giáo (TQ)",
  "国庆节": "Quốc khánh (TQ)",
  "万圣节": "Halloween",
  "感恩节": "Lễ Tạ ơn",
  "平安夜": "Đêm Giáng sinh",
  "圣诞节": "Giáng sinh",
  "命互禄": "mệnh hỗ lộc",
  "命进禄": "mệnh tiến lộc",
  "四时会": "Tứ thời hội",
  "祭灶王": "Cúng Táo Vương",
  "五行会": "Ngũ hành hội",
  "星辰会": "Tinh thần hội",
  "始电": "Chớp bắt đầu",
  "既朔": "Ký Sóc",
  "蛾眉": "Nga mi",
  "上弦": "Thượng huyền",
  "小望": "Tiểu vọng",
  "既望": "Ký Vọng",
  "立待": "Lập đãi",
  "居待": "Cư đãi",
  "寝待": "Tẩm đãi",
  "更待": "Canh đãi",
  "下弦": "Hạ huyền",
  "有明": "Hữu minh",
  "九夜": "Cửu dạ",
  "大安": "Đại An",
  "留连": "Lưu Liên",
  "速喜": "Tốc Hỷ",
  "赤口": "Xích Khẩu",
  "小吉": "Tiểu cát",
  "空亡": "Không Vong",
  "先胜": "Tiên thắng",
  "友引": "Hữu dẫn",
  "先负": "Tiên bại",
  "佛灭": "Phật diệt",
  "大吉": "Đại cát",
  "一九": "Nhất cửu",
  "二九": "Nhị cửu",
  "三九": "Tam cửu",
  "四九": "Tứ cửu",
  "五九": "Ngũ cửu",
  "六九": "Lục cửu",
  "七九": "Thất cửu",
  "八九": "Bát cửu",
  "九九": "Cửu cửu",
  "了戾": "Liễu Lệ",
  "单阴": "Đơn Âm",
  "纯阳": "Thuần Dương",
  "天枢": "Thiên Xu",
  "天璇": "Thiên Toàn",
  "天玑": "Thiên Cơ",
  "天权": "Thiên Quyền",
  "玉衡": "Ngọc Hành",
  "开阳": "Khai Dương",
  "摇光": "Dao Quang",
  "洞明": "Động Minh",
  "隐元": "Ẩn Nguyên",
  "玄空": "Huyền Không",
  "奇门": "Kỳ Môn",
  "太乙": "Thái Ất",
  "贪狼": "Tham Lang",
  "巨门": "Cự Môn",
  "禄存": "Lộc Tồn",
  "文曲": "Văn Khúc",
  "廉贞": "Liêm Trinh",
  "武曲": "Vũ Khúc",
  "破军": "Phá Quân",
  "左辅": "Tả Phụ",
  "右弼": "Hữu Bật",
  "天蓬": "Thiên Bồng",
  "天芮": "Thiên Nhuế",
  "天冲": "Thiên Xung",
  "天辅": "Thiên Phụ",
  "天禽": "Thiên Cầm",
  "天心": "Thiên Tâm",
  "天柱": "Thiên Trụ",
  "天任": "Thiên Nhậm",
  "天英": "Thiên Anh",
  "休门": "Hưu môn",
  "死门": "Tử môn",
  "伤门": "Thương môn",
  "杜门": "Đỗ môn",
  "开门": "Khai môn",
  "惊门": "Kinh môn",
  "生门": "Sinh môn",
  "景门": "Cảnh môn",
  "大凶": "Đại hung",
  "小凶": "Tiểu hung",
  "吉神": "Cát thần",
  "凶神": "Hung thần",
  "安神": "An thần",
  "摄提": "Nhiếp Đề",
  "轩辕": "Hiên Viên",
  "招摇": "Chiêu Dao",
  "天符": "Thiên Phù",
  "咸池": "Hàm Trì",
  "太阴": "Thái Âm",
  "青龙": "Thanh Long",
  "天乙": "Thiên Ất",
  "正北": "chính Bắc",
  "西南": "Tây Nam",
  "正东": "chính Đông",
  "东南": "Đông Nam",
  "中宫": "Trung cung",
  "西北": "Tây Bắc",
  "正西": "chính Tây",
  "东北": "Đông Bắc",
  "正南": "chính Nam",
  "春节": "Tết Nguyên đán (TQ)",
  "除夕": "Giao thừa",
  "人日": "Ngày Nhân",
  "春社": "Xuân xã",
  "秋社": "Thu xã",
  "尾牙": "Vĩ Nha",
  "地日": "Ngày Địa",
  "天日": "Ngày Thiên",
  "谷日": "Ngày Cốc",
  "互禄": "hỗ lộc",
  "进禄": "tiến lộc",
  "初候": "sơ hậu",
  "二候": "nhị hậu",
  "三候": "tam hậu",
  "一候": "nhất hậu",
  "日会": "Nhật hội",
  "地会": "Địa hội",
  "天会": "Thiên hội",
  "人会": "Nhân hội",
  "月会": "Nguyệt hội",
  "朔": "Sóc",
  "夕": "Tịch",
  "宵": "Tiêu",
  "望": "Vọng",
  "晓": "Hiểu",
  "残": "Tàn",
  "晦": "Hối",
  "彘": "Heo",
  "獝": "Huýt",
  "日": "Nhật",
  "月": "tháng",
  "一": "Nhất",
  "七": "Thất",
  "万": "Vạn",
  "三": "Tam",
  "上": "Thượng",
  "不": "Bất",
  "世": "Thế",
  "东": "Đông",
  "丰": "Phong",
  "丹": "Đan",
  "乙": "Ất",
  "九": "Cửu",
  "二": "Nhị",
  "五": "Ngũ",
  "人": "Nhân",
  "仙": "Tiên",
  "代": "Đại",
  "何": "Hà",
  "佗": "Đà",
  "侯": "Hầu",
  "先": "Tiên",
  "光": "Quang",
  "公": "Công",
  "关": "Quan",
  "农": "Nông",
  "刘": "Lưu",
  "勾": "Câu",
  "化": "Hóa",
  "北": "Bắc",
  "医": "Y",
  "十": "Thập",
  "华": "Hoa",
  "南": "Nam",
  "即": "tức",
  "司": "Tư",
  "同": "đồng",
  "后": "Hậu",
  "君": "Quân",
  "命": "Mệnh",
  "土": "Thổ",
  "圣": "Thánh",
  "地": "Địa",
  "增": "Tăng",
  "处": "Xử",
  "大": "Đại",
  "天": "Thiên",
  "太": "Thái",
  "好": "Hảo",
  "妙": "Diệu",
  "始": "Thủy",
  "姑": "Cô",
  "姜": "Khương",
  "姥": "Mẫu",
  "子": "Tử",
  "孙": "Tôn",
  "官": "Quan",
  "宝": "Bảo",
  "宸": "Thần",
  "山": "Sơn",
  "岁": "Tuế",
  "岳": "Nhạc",
  "帛": "Bạch",
  "帝": "Đế",
  "平": "Bình",
  "应": "Ứng",
  "度": "Độ",
  "弘": "Hoằng",
  "张": "Trương",
  "微": "Vi",
  "德": "Đức",
  "悟": "Ngộ",
  "救": "Cứu",
  "文": "Văn",
  "斗": "Đẩu",
  "无": "Vô",
  "昌": "Xương",
  "星": "Tinh",
  "春": "Xuân",
  "显": "Hiển",
  "曹": "Tào",
  "机": "Cơ",
  "李": "Lý",
  "极": "Cực",
  "梓": "Tử",
  "梵": "Phạm",
  "正": "Chính",
  "母": "Mẫu",
  "民": "Dân",
  "泰": "Thái",
  "海": "Hải",
  "清": "Thanh",
  "渊": "Uyên",
  "温": "Ôn",
  "湘": "Tương",
  "潼": "Đồng",
  "火": "Hỏa",
  "灵": "Linh",
  "炁": "Khí",
  "然": "Nhiên",
  "爷": "Gia",
  "猷": "Du",
  "玄": "Huyền",
  "玉": "Ngọc",
  "王": "Vương",
  "班": "Ban",
  "生": "Sinh",
  "白": "Bạch",
  "皇": "Hoàng",
  "相": "Tướng",
  "真": "Chân",
  "眼": "Nhãn",
  "碧": "Bích",
  "祖": "Tổ",
  "祗": "Chi",
  "神": "Thần",
  "福": "Phúc",
  "离": "Ly",
  "端": "Đoan",
  "素": "Tố",
  "紫": "Tử",
  "翁": "Ông",
  "老": "Lão",
  "腊": "Lạp",
  "至": "Chí",
  "苦": "Khổ",
  "茅": "Mao",
  "萨": "Tát",
  "葛": "Cát",
  "虚": "Hư",
  "蟾": "Thiềm",
  "许": "Hứa",
  "诡": "Quỷ",
  "诸": "Chư",
  "谭": "Đàm",
  "谷": "Cốc",
  "财": "Tài",
  "赤": "Xích",
  "赵": "Triệu",
  "逊": "Tốn",
  "道": "Đạo",
  "邓": "Đặng",
  "邱": "Khâu",
  "郎": "Lang",
  "郝": "Hách",
  "都": "Đô",
  "酆": "Phong",
  "量": "Lượng",
  "钟": "Chung",
  "长": "Trường",
  "阳": "Dương",
  "阴": "Âm",
  "陈": "Trần",
  "降": "Giáng",
  "雷": "Lôi",
  "霆": "Đình",
  "霞": "Hà",
  "青": "Thanh",
  "靖": "Tĩnh",
  "静": "Tĩnh",
  "韩": "Hàn",
  "马": "Mã",
  "鬼": "Quỷ",
  "鲁": "Lỗ",
  "黑": "Hắc",
  "吉": "Tốt",
  "凶": "Xấu",
  "年": "năm",
  "坎": "Khảm",
  "坤": "Khôn",
  "震": "Chấn",
  "巽": "Tốn",
  "乾": "Càn",
  "兑": "Đoài",
  "艮": "Cấn",
  "中": "Trung",
};

export const CHAR_SV: Record<string, string> = {
  "一": "Nhất",
  "七": "Thất",
  "万": "Vạn",
  "三": "Tam",
  "上": "Thượng",
  "不": "Bất",
  "世": "Thế",
  "东": "Đông",
  "丰": "Phong",
  "丹": "Đan",
  "乙": "Ất",
  "九": "Cửu",
  "二": "Nhị",
  "五": "Ngũ",
  "人": "Nhân",
  "仙": "Tiên",
  "代": "Đại",
  "何": "Hà",
  "佗": "Đà",
  "侯": "Hầu",
  "先": "Tiên",
  "光": "Quang",
  "公": "Công",
  "关": "Quan",
  "农": "Nông",
  "刘": "Lưu",
  "勾": "Câu",
  "化": "Hóa",
  "北": "Bắc",
  "医": "Y",
  "十": "Thập",
  "华": "Hoa",
  "南": "Nam",
  "即": "tức",
  "司": "Tư",
  "同": "đồng",
  "后": "Hậu",
  "君": "Quân",
  "命": "Mệnh",
  "土": "Thổ",
  "圣": "Thánh",
  "地": "Địa",
  "增": "Tăng",
  "处": "Xử",
  "大": "Đại",
  "天": "Thiên",
  "太": "Thái",
  "好": "Hảo",
  "妙": "Diệu",
  "始": "Thủy",
  "姑": "Cô",
  "姜": "Khương",
  "姥": "Mẫu",
  "子": "Tử",
  "孙": "Tôn",
  "官": "Quan",
  "宝": "Bảo",
  "宸": "Thần",
  "山": "Sơn",
  "岁": "Tuế",
  "岳": "Nhạc",
  "帛": "Bạch",
  "帝": "Đế",
  "平": "Bình",
  "应": "Ứng",
  "度": "Độ",
  "弘": "Hoằng",
  "张": "Trương",
  "微": "Vi",
  "德": "Đức",
  "悟": "Ngộ",
  "救": "Cứu",
  "文": "Văn",
  "斗": "Đẩu",
  "无": "Vô",
  "日": "Nhật",
  "昌": "Xương",
  "星": "Tinh",
  "春": "Xuân",
  "显": "Hiển",
  "曹": "Tào",
  "机": "Cơ",
  "李": "Lý",
  "极": "Cực",
  "梓": "Tử",
  "梵": "Phạm",
  "正": "Chính",
  "母": "Mẫu",
  "民": "Dân",
  "泰": "Thái",
  "海": "Hải",
  "清": "Thanh",
  "渊": "Uyên",
  "温": "Ôn",
  "湘": "Tương",
  "潼": "Đồng",
  "火": "Hỏa",
  "灵": "Linh",
  "炁": "Khí",
  "然": "Nhiên",
  "爷": "Gia",
  "猷": "Du",
  "玄": "Huyền",
  "玉": "Ngọc",
  "王": "Vương",
  "班": "Ban",
  "生": "Sinh",
  "白": "Bạch",
  "皇": "Hoàng",
  "相": "Tướng",
  "真": "Chân",
  "眼": "Nhãn",
  "碧": "Bích",
  "祖": "Tổ",
  "祗": "Chi",
  "神": "Thần",
  "福": "Phúc",
  "离": "Ly",
  "端": "Đoan",
  "素": "Tố",
  "紫": "Tử",
  "翁": "Ông",
  "老": "Lão",
  "腊": "Lạp",
  "至": "Chí",
  "苦": "Khổ",
  "茅": "Mao",
  "萨": "Tát",
  "葛": "Cát",
  "虚": "Hư",
  "蟾": "Thiềm",
  "许": "Hứa",
  "诡": "Quỷ",
  "诸": "Chư",
  "谭": "Đàm",
  "谷": "Cốc",
  "财": "Tài",
  "赤": "Xích",
  "赵": "Triệu",
  "逊": "Tốn",
  "道": "Đạo",
  "邓": "Đặng",
  "邱": "Khâu",
  "郎": "Lang",
  "郝": "Hách",
  "都": "Đô",
  "酆": "Phong",
  "量": "Lượng",
  "钟": "Chung",
  "长": "Trường",
  "阳": "Dương",
  "阴": "Âm",
  "陈": "Trần",
  "降": "Giáng",
  "雷": "Lôi",
  "霆": "Đình",
  "霞": "Hà",
  "青": "Thanh",
  "靖": "Tĩnh",
  "静": "Tĩnh",
  "韩": "Hàn",
  "马": "Mã",
  "鬼": "Quỷ",
  "鲁": "Lỗ",
  "黑": "Hắc",
  "吉": "Tốt",
  "凶": "Xấu",
  "年": "năm",
  "月": "tháng",
  "坎": "Khảm",
  "坤": "Khôn",
  "震": "Chấn",
  "巽": "Tốn",
  "乾": "Càn",
  "兑": "Đoài",
  "艮": "Cấn",
  "中": "Trung",
};
